In [78]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

In [79]:
from sklearn.datasets import load_iris
iris = load_iris()

In [80]:
#iris

In [81]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [82]:
#iris.DESCR

In [83]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [84]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [85]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)   # "feature name" is input column and "target" is output column.
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [87]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [88]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [89]:
df['target'] = iris.target  # Adding new column in dataframe
df.head()                 # Key Value pair,key is"target""iris.target"is value.

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [90]:
df.sample(10) 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
23                 5.1               3.3                1.7               0.5   
77                 6.7               3.0                5.0               1.7   
83                 6.0               2.7                5.1               1.6   
86                 6.7               3.1                4.7               1.5   
35                 5.0               3.2                1.2               0.2   
29                 4.7               3.2                1.6               0.2   
69                 5.6               2.5                3.9               1.1   
143                6.8               3.2                5.9               2.3   
116                6.5               3.0                5.5               1.8   
146                6.3               2.5                5.0               1.9   

     target  
23        0  
77        1  
83        1  
86        1  
35        0  
29        0  
69        1  
143       2  
116       2  
146       2

In [91]:
df[df.target==0].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [92]:
df[df.target==0].shape

(50, 5)

In [93]:
df[df.target==1].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
50                7.0               3.2                4.7               1.4   
51                6.4               3.2                4.5               1.5   
52                6.9               3.1                4.9               1.5   
53                5.5               2.3                4.0               1.3   
54                6.5               2.8                4.6               1.5   

    target  
50       1  
51       1  
52       1  
53       1  
54       1

In [94]:
df[df.target==1].shape

(50, 5)

In [95]:
df['target'].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [96]:
df.target.sample(10)

3      0
0      0
57     1
76     1
120    2
30     0
60     1
35     0
92     1
68     1
Name: target, dtype: int32

In [97]:
df['flower_name'] = df.target.apply(lambda x:iris.target_names[x])
df.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
142                5.8               2.7                5.1               1.9   
6                  4.6               3.4                1.4               0.3   
38                 4.4               3.0                1.3               0.2   
138                6.0               3.0                4.8               1.8   
122                7.7               2.8                6.7               2.0   

     target flower_name  
142       2   virginica  
6         0      setosa  
38        0      setosa  
138       2   virginica  
122       2   virginica

In [98]:
# Train using Support Vector Machinr(SVM)
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [99]:
x = df.drop(['target','flower_name'],axis = 'columns')
y = df.target

In [100]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

In [101]:
len(x_train)

120

In [102]:
len(x_test)

30

In [103]:
len(y_train)

120

In [104]:
len(y_test)

30

#### Apply Model 
##### when doing 'classification', we need: 'Classification Report'& 'Confusion Matrix'

In [105]:
from sklearn.svm import SVC #'Support Vector Classifier'
model = SVC()               # we doing classification that's why 'SVC'

In [106]:
# fit the model 
model.fit(x_train,y_train)

SVC()

In [107]:
y_test

129    2
145    2
93     1
116    2
141    2
64     1
118    2
125    2
137    2
138    2
11     0
88     1
40     0
17     0
110    2
148    2
135    2
0      0
108    2
121    2
65     1
147    2
10     0
22     0
43     0
34     0
106    2
16     0
127    2
84     1
Name: target, dtype: int32

In [110]:
y_pred = model.predict(x_test)
y_pred

array([2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 0, 1, 0, 0, 2, 2, 2, 0, 2, 2, 1, 2,
       0, 0, 0, 0, 1, 0, 1, 1])

In [111]:
model.score(x_test,y_test)

0.9

In [115]:
#x_test

In [116]:
model.predict([[6.1,3.0,4.9,1.8]]) # the answer tells to which class it belongs[1]

C:\Users\anamn\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1])

In [118]:
# evaluate the mmodel
print(confusion_matrix(y_test, y_pred))

[[ 9  0  0]
 [ 0  5  0]
 [ 0  3 13]]


In [120]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.62      1.00      0.77         5
           2       1.00      0.81      0.90        16

    accuracy                           0.90        30
   macro avg       0.88      0.94      0.89        30
weighted avg       0.94      0.90      0.91        30

